Fix/remove message
Unifacs-Equipe-1/P-presence pull request #4
Opened 2024-06-09 20:59 UTC by marcelatmb

Correção de tabulações e limpeza da tela

2024-06-09 21:07 UTC, erick-gomes commented
O branch tem alguns commits atrás da main, faz o git merge da main para esse branch e resolve os conflitos

2024-06-09 21:48 UTC, erick-gomes commented on P-presence
Excluir subpasta com nome do projeto

2024-06-09 22:00 UTC, erick-gomes commented on src/controllers/logins/admin/gerenciar/filtroAlunos/FiltrarAlunosController.java
> +			Util.limparTela();
Não é recomendado limpar a tela antes de apresentar as mensagens, pois pode apagar um log anterior que não foi identificado. Necessário buscar as ocorrências de todos os métodos limparTela() que fazem isso antes de printar algo na tela e adicioná-los somente ao final de alguma função, que queira limpar o log.

2024-06-09 22:04 UTC, erick-gomes commented
Alguns logs ainda estão sendo apresentados fora da tela de sistema unifacs, seria interessante implementar uma maneira de deixar tudo dentro de uma caixa, seja logs ou confirmações, ou somente remover os logs que ficam de fora acima do painel, corretamente.

2024-06-09 22:06 UTC, marcelatmb commented on src/controllers/logins/admin/gerenciar/filtroAlunos/FiltrarAlunosController.java
> +			Util.limparTela();
Estava dando erro e ficando duplicado. Posso revisar isso agora.

2024-06-09 22:08 UTC, marcelatmb commented on P-presence
Que pasta é esta? Não criei nenhuma.

2024-06-09 22:12 UTC, erick-gomes commented on P-presence
> Que pasta é esta? Não criei nenhuma.

![Captura de tela de 2024-06-09 19-11-27](https://github.com/Unifacs-Portfolio/P-presence/assets/73054413/10284a97-1a6d-442b-bd90-f90a1a7817b5)

2024-06-10 01:51 UTC, MarcilioFilh0 requested changes
Na linha 163 de GerenciarProfessor, tem um colchete a mais
Tem que remover, pois está apontando como erro

2024-06-10 01:51 UTC, erick-gomes commented on src/controllers/logins/admin/gerenciar/GerenciarProfessoresController.java
> +					Util.limparTela();
Os métodos de limparTela não devem ficar dentro do switch com o controller

2024-06-10 02:04 UTC, erick-gomes commented on src/controllers/logins/admin/AdministradorController.java
> +				System.out.println("Pressione enter para responder...");
Não ficou muito legal o "Pressione enter para responder", pois procede uma pergunta de sim ou não que só pode ser respondida pelo painel

2024-06-10 02:05 UTC, erick-gomes commented on src/controllers/logins/admin/AdministradorController.java
> +						System.out.print("\nPressione enter para prosseguir...");
Não é necessário informar quando ele retorna a página inicial, pois ele já confirma que não deseja tentar denovo

2024-06-10 02:08 UTC, erick-gomes commented on src/controllers/logins/admin/gerenciar/GerenciarAlunosController.java
> +		System.out.println("Pressione enter definir o que deseja modificar...");
Ficou ilógico pedir para inserir enter para dizer o que deseja modificar

2024-06-10 02:09 UTC, erick-gomes commented on src/controllers/logins/admin/gerenciar/GerenciarAlunosController.java
> +		System.out.println("Aluno encontrado, tem certeza que deseja excluir?");
Implementar a pergunta no aluno foi uma boa implementação, mas contém o pressione responder relatado nos comentários anteriores

2024-06-10 02:11 UTC, erick-gomes commented on src/controllers/logins/admin/gerenciar/GerenciarAlunosController.java
> +					Util.limparTela();
método limparTela() não deve ficar no switch dos controllers do aluno

2024-06-10 02:13 UTC, erick-gomes commented on src/controllers/logins/aluno/AlunoController.java
> -				return;
Erro grave permite que avançe na verificação de usuário, mesmo o RA não sendo encontrado

2024-06-10 02:15 UTC, erick-gomes requested changes
Necessário remover o método de limpar tela do lugar onde é executado os controllers e remover o "pressione enter para responder" em todas as ocorrências

2024-06-10 18:13 UTC, erick-gomes submitted a review, later dismissed
Antes de aprovar essa PR, necessário aprovar as PRs #8 e #7

2024-06-10 22:21 UTC, MarcilioFilh0 submitted a review, later dismissed

2024-06-10 22:44 UTC, MarcilioFilh0 commented on src/controllers/logins/aluno/AlunoController.java
> -				return;
Erick, aonde está o erro?

2024-06-10 23:02 UTC, RodsonSSJunior approved these changes

2024-06-10 23:02 UTC, MarcilioFilh0 approved these changes

2024-06-10 23:03 UTC, merged