Attributes
Unifacs-Equipe-1/P-presence pull request #5
Opened 2024-06-09 21:10 UTC by ArthurOrnelas

criação de novos atributos a classe aluno e professor

2024-06-09 21:18 UTC, erick-gomes commented
O branch não pode ter commits atrás da main, sempre verifique se o repositório tem somente commits a frente da main, caso contrário faça o merge e resolva os conflitos

2024-06-10 00:48 UTC, erick-gomes commented on src/models/Aluno.java
> +	public String getRegistro_aluno() {
Remover método getRegisto_aluno(), um método getRa() já existe

2024-06-10 00:55 UTC, erick-gomes commented on src/models/Aluno.java
> +	public void setPresente(Boolean presente) {
método setPresente não é necessário

2024-06-10 00:58 UTC, MarcilioFilh0 commented on src/models/Professor.java
Graduação está okey, mas é necessário colocar um a mais, que seja diferente de algum atributo do aluno,
Por exemplo, aluno tem "semestre e gênero" que os professores não tem

2024-06-10 00:59 UTC, erick-gomes requested changes
Necessário remover métodos não utilizados

2024-06-10 01:03 UTC, MarcilioFilh0 reviewed
Graduação está okey, mas é necessário colocar um a mais, que seja diferente de algum atributo do aluno,
Por exemplo, aluno tem "semestre e gênero" que os professores não tem

2024-06-11 01:27 UTC, erick-gomes approved these changes

2024-06-11 01:28 UTC, MarcilioFilh0 approved these changes

2024-06-11 01:30 UTC, merged